name: Cypress Tests
on: 
  push:
    branches:
      - 'main' 
      
  schedule:
    - cron: '05 21 14 8 1'

jobs:
 Cypress-Test:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout GitCode
       uses: actions/checkout@v2
 
     - name: Run Cypress Test
       uses: cypress-io/github-action@v4
       with:
         command: npx cypress run
         browser: chrome